GET http://localhost:3000/tasks

###

GET http://localhost:3000/tasks/60bb11ee1e0c779b2c0c9181

###

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name": "Feed Toad"
}

###

DELETE http://localhost:3000/tasks/60bb11ee1e0c779b2c0c9181

###
PATCH http://localhost:3000/tasks/60bb126b83302d9b638db848
Content-Type: application/json

{
    "name": "Feed cats"
}
